class Categories {
  static List categoriesList = [
    "Random",
    "Clean",
    "Relationship",
    "School",
    "Animal",
    "Deep Thoughts",
    "Jewish",
    "Food",
    "Dark",
    "Racist",
    "Sexual",
    "One Liner",
    "Insults",
    "Knock Knock",
    "Political",
    "Sexist",
    "Sport",
    "Chuck Norris",
    "Holiday",
    "Blondes",
    "Yo Momma",
    "Analogy",
    "Law",
    "NSFW",
    "Christmas",
    "Nerdy",
    "Religious",
    "Kids"
  ];
}
